 version: '2'

 services:
   emparejamiento-ms:
     build: .
     command: python3 manage.py runserver 0.0.0.0:4004
     ports:
       - "4004:4004"
     depends_on:
       - emparejamiento-db
   emparejamiento-db:
     image: postgres
     ports:
       - "5434:5432"
